#网站配置
website:
  #网站名
  name: 自由分享的免费小说网站，无弹窗，无广告
  #域名
  domain: www.share.中国
  #SEO关键词
  keyword: ${website.name},免费小说,小说分享,激情小说,原创文学系统
  #SEO描述
  description: ${website.name}是一个免费的，自由的，清爽的网络小说网站，所有资源来源于网络，如果侵权，请联系站长，我们会尽快删除 。阅读，让生活更多姿多彩，未成年请适度阅读，请在成人监督下阅读小说。
  #联系QQ
  微信:
